version: '2'
services:
  db:
    image: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
    ports:
      - "5433:5432"
    volumes:
      - datastore:/var/lib/postgresql/data
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "5000:5000"
volumes:
  datastore:
    driver: local
