version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    volumes_from:
      - datastore
    command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
  db:
    image: postgres
    volumes_from:
      - datastore
    environment:
      POSTGRES_PASSWORD: pss
      POSTGRES_USER: usr
      POSTGRES_DB: dbb
    env_file:
      - '.env'      
volumes:
  db-data:
    driver: local
