default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  pool: 5
  timeout: 5000
  username: local
  password: 

development:
  <<: *default
  database: wakatime_console

test:
  <<: *default
  database: wakatime_console_test

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_DB'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PW'] %>
